name: CI-CD

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Depencencies Install
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test:ci
