name: Hola mundo!

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Hola mundo!
      run: echo "Hola mundo!"
